import React, { useState } from 'react';
import { RichTextRenderer } from './RichTextRenderer';

// Example HTML content that would be generated by the rich text editor
const sampleContent = `
<h1>Welcome to Rich Text Renderer</h1>
<p>This is a <strong>standalone component</strong> for rendering HTML content generated by the rich text editor.</p>

<h2>Features</h2>
<ul>
  <li>Typography support (headings, paragraphs, text formatting)</li>
  <li>Lists (ordered, unordered, task lists)</li>
  <li>Code blocks and inline code</li>
  <li>Tables, images, and links</li>
  <li>Dark mode support</li>
</ul>

<h3>Code Example</h3>
<pre><code>import { RichTextRenderer } from 'rich-text-editor/renderer';

function MyComponent() {
  return &lt;RichTextRenderer content={htmlContent} /&gt;;
}</code></pre>

<blockquote class="blockquote">
This renderer is lightweight and doesn't include any editor dependencies, making it perfect for displaying content.
</blockquote>

<h3>Task List Example</h3>
<ul data-type="taskList">
  <li data-checked="true">
    <label><input type="checkbox" checked disabled /></label>
    <div>Completed task</div>
  </li>
  <li data-checked="false">
    <label><input type="checkbox" disabled /></label>
    <div>Pending task</div>
  </li>
</ul>

<p>Visit our <a href="#" class="link">documentation</a> for more examples.</p>

<hr data-type="horizontalRule" />

<p><em>Thank you for using Rich Text Renderer!</em></p>
`;

const complexContent = `
<h1>Advanced Content Example</h1>

<table>
  <thead>
    <tr>
      <th>Feature</th>
      <th>Supported</th>
      <th>Notes</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Headings</td>
      <td>✅</td>
      <td>H1 through H6</td>
    </tr>
    <tr>
      <td>Lists</td>
      <td>✅</td>
      <td>Ordered, unordered, tasks</td>
    </tr>
    <tr>
      <td>Images</td>
      <td>✅</td>
      <td>Responsive sizing</td>
    </tr>
  </tbody>
</table>

<p>Text can be <strong>bold</strong>, <em>italic</em>, <u>underlined</u>, <s>strikethrough</s>, and <mark>highlighted</mark>.</p>

<p data-text-align="center">This paragraph is center-aligned.</p>
<p data-text-align="right">This paragraph is right-aligned.</p>

<p data-indent="1">This text is indented once.</p>
<p data-indent="2">This text is indented twice.</p>
<p data-indent="3">This text is indented three times.</p>
`;

export function RendererExample() {
  const [content, setContent] = useState(sampleContent);
  const [isDark, setIsDark] = useState(false);

  return (
    <div style={{ padding: '2rem', maxWidth: '800px', margin: '0 auto' }}>
      <div style={{ marginBottom: '2rem' }}>
        <h1>Rich Text Renderer Examples</h1>

        <div style={{ marginBottom: '1rem' }}>
          <button
            onClick={() => setContent(sampleContent)}
            style={{ marginRight: '1rem', padding: '0.5rem 1rem' }}
          >
            Basic Content
          </button>
          <button
            onClick={() => setContent(complexContent)}
            style={{ marginRight: '1rem', padding: '0.5rem 1rem' }}
          >
            Complex Content
          </button>
          <label style={{ marginLeft: '1rem' }}>
            <input
              type="checkbox"
              checked={isDark}
              onChange={(e) => setIsDark(e.target.checked)}
              style={{ marginRight: '0.5rem' }}
            />
            Dark Mode
          </label>
        </div>
      </div>

      <div
        style={{
          border: '1px solid #e5e7eb',
          borderRadius: '0.5rem',
          padding: '1.5rem',
          backgroundColor: isDark ? '#1f2937' : '#ffffff'
        }}
      >
        <RichTextRenderer
          content={content}
          dark={isDark}
          className="example-renderer"
        />
      </div>

      <div style={{ marginTop: '2rem', fontSize: '0.875rem', color: '#6b7280' }}>
        <h3>Usage:</h3>
        <pre style={{
          backgroundColor: '#f3f4f6',
          padding: '1rem',
          borderRadius: '0.25rem',
          overflow: 'auto'
        }}>
{`import { RichTextRenderer } from 'rich-text-editor/renderer';

function MyComponent() {
  const htmlContent = '...'; // HTML from your rich text editor

  return (
    <RichTextRenderer
      content={htmlContent}
      dark={${isDark}}
      className="my-custom-class"
    />
  );
}`}
        </pre>
      </div>
    </div>
  );
}

export default RendererExample;
