declare module 'rich-text-editor/renderer' {
  import { FC } from 'react';

  export interface RichTextRendererProps {
    /** HTML content to render */
    content: string;
    /** Additional CSS class names */
    className?: string;
    /** Dark mode flag */
    dark?: boolean;
    /** Custom styles */
    style?: React.CSSProperties;
  }

  /**
   * RichTextRenderer - A standalone component for rendering HTML content
   * generated by the rich text editor without requiring the full editor setup.
   */
  export const RichTextRenderer: FC<RichTextRendererProps>;
  export default RichTextRenderer;
}

declare module 'rich-text-editor/renderer/style.css' {
  const content: string;
  export default content;
}
