import React from 'react';

/**
 * Props for the RichTextRenderer component
 */
export interface RichTextRendererProps {
  /** HTML content to render */
  content: string;
  /** Additional CSS class names */
  className?: string;
  /** Dark mode flag */
  dark?: boolean;
  /** Custom styles */
  style?: React.CSSProperties;
}

/**
 * RichTextRenderer - A standalone component for rendering HTML content
 * generated by the rich text editor without requiring the full editor setup.
 */
export const RichTextRenderer: React.FC<RichTextRendererProps> = ({
  content,
  className = '',
  dark = false,
  style,
}) => {
  const baseStyles: React.CSSProperties = {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',
    lineHeight: 1.6,
    color: dark ? '#e2e8f0' : '#1a202c',
    backgroundColor: dark ? '#1a202c' : '#ffffff',
    ...style,
  };

  // Comprehensive inline styles for all content types
  const rendererStyles = `
    <style>
      .richtext-renderer p {
        line-height: 1.625;
        margin-bottom: 1.5rem;
      }
      .richtext-renderer p:first-child { margin-top: 0; }
      .richtext-renderer p:last-child { margin-bottom: 0; }

      .richtext-renderer h1 { font-size: 1.875rem; font-weight: 700; margin-top: 3rem; margin-bottom: 1rem; }
      .richtext-renderer h2 { font-size: 1.5rem; font-weight: 700; margin-top: 3rem; margin-bottom: 1rem; }
      .richtext-renderer h3 { font-size: 1.25rem; font-weight: 700; margin-top: 3rem; margin-bottom: 1rem; }
      .richtext-renderer h4 { font-size: 1.125rem; font-weight: 700; margin-top: 2rem; margin-bottom: 1rem; }
      .richtext-renderer h5 { font-size: 1rem; font-weight: 700; margin-top: 2rem; margin-bottom: 1rem; }
      .richtext-renderer h6 { font-size: 0.875rem; font-weight: 700; margin-top: 2rem; margin-bottom: 1rem; }
      .richtext-renderer h1:first-child, .richtext-renderer h2:first-child, .richtext-renderer h3:first-child,
      .richtext-renderer h4:first-child, .richtext-renderer h5:first-child, .richtext-renderer h6:first-child { margin-top: 0; }
      .richtext-renderer h1:last-child, .richtext-renderer h2:last-child, .richtext-renderer h3:last-child,
      .richtext-renderer h4:last-child, .richtext-renderer h5:last-child, .richtext-renderer h6:last-child { margin-bottom: 0; }

      .richtext-renderer a.link { color: ${
        dark ? '#60a5fa' : '#3b82f6'
      }; font-weight: 800; text-decoration: underline; }
      .richtext-renderer a.link:hover { color: ${
        dark ? '#93c5fd' : '#2563eb'
      }; }

      .richtext-renderer strong { font-weight: 700; }
      .richtext-renderer em { font-style: italic; }
      .richtext-renderer u { text-decoration: underline; }
      .richtext-renderer s { text-decoration: line-through; }
      .richtext-renderer mark { background-color: ${
        dark ? '#dc2626' : '#ef4444'
      }; color: inherit; border-radius: 0.125rem; padding: 0.25rem 0; }

      .richtext-renderer code { background-color: #374151; color: #ffffff; border-radius: 0.125rem; padding: 0.125rem 0.25rem; font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace; font-size: 0.875em; }
      .richtext-renderer pre { background-color: ${
        dark ? '#111827' : '#4b5563'
      }; color: #ffffff; border-radius: 0.375rem; margin: 3rem 0; padding: 1rem; border: 1px solid ${
        dark ? '#374151' : '#000000'
      }; overflow-x: auto; }
      .richtext-renderer pre:first-child { margin-top: 0; }
      .richtext-renderer pre:last-child { margin-bottom: 0; }
      .richtext-renderer pre code { background-color: inherit; color: inherit; padding: 0; }

      .richtext-renderer .blockquote, .richtext-renderer blockquote {
        border-left: 4px solid ${dark ? '#d1d5db' : '#4b5563'};
        color: ${dark ? '#ffffff' : '#000000'};
        padding: 0.5rem 1rem;
        background-color: ${
          dark ? 'rgba(255, 255, 255, 0.05)' : 'rgba(0, 0, 0, 0.05)'
        };
        border-radius: 0.5rem;
        border-top-left-radius: 0;
        border-bottom-left-radius: 0;
        margin: 1.5rem 0;
      }
      .richtext-renderer .blockquote:first-child, .richtext-renderer blockquote:first-child { margin-top: 0; }
      .richtext-renderer .blockquote:last-child, .richtext-renderer blockquote:last-child { margin-bottom: 0; }

      .richtext-renderer ol { list-style-type: decimal; padding-left: 2rem; margin: 1.5rem 0; }
      .richtext-renderer ul { list-style-type: disc; padding-left: 2rem; margin: 1.5rem 0; }
      .richtext-renderer ul:first-child, .richtext-renderer ol:first-child { margin-top: 0; }
      .richtext-renderer ul:last-child, .richtext-renderer ol:last-child { margin-bottom: 0; }
      .richtext-renderer ul ul, .richtext-renderer ul ol, .richtext-renderer ul li,
      .richtext-renderer ol ul, .richtext-renderer ol ol, .richtext-renderer ol li { margin: 0.25rem 0; }
      .richtext-renderer ul p, .richtext-renderer ol p { margin-top: 0; margin-bottom: 0.25rem; }

      .richtext-renderer ul[data-type="taskList"] { list-style: none; padding: 0; }
      .richtext-renderer ul[data-type="taskList"] p { margin: 0; }
      .richtext-renderer ul[data-type="taskList"] li { display: flex; align-items: flex-start; }
      .richtext-renderer ul[data-type="taskList"] li > label { flex: none; margin-right: 0.5rem; user-select: none; }
      .richtext-renderer ul[data-type="taskList"] li > div { flex: 1; }
      .richtext-renderer ul[data-type="taskList"] li[data-checked="true"] { text-decoration: line-through; }

      .richtext-renderer img { height: auto; max-width: 100%; border-radius: 0.375rem; }

      .richtext-renderer iframe { border: 1px solid ${
        dark ? '#374151' : '#e5e7eb'
      }; width: 100%; margin-top: 0.5rem; border-radius: 0.125rem; height: 100%; }

      .richtext-renderer [data-type="horizontalRule"] { margin: 2rem 0; padding: 1rem 0; }
      .richtext-renderer [data-type="horizontalRule"] hr {
        border: 0;
        border-top: 1px solid ${
          dark ? 'rgba(255, 255, 255, 0.2)' : 'rgba(0, 0, 0, 0.2)'
        };
        background-color: ${
          dark ? 'rgba(255, 255, 255, 0.8)' : 'rgba(0, 0, 0, 0.8)'
        };
      }

      .richtext-renderer table {
        border: 1px solid ${
          dark ? 'rgba(255, 255, 255, 0.2)' : 'rgba(0, 0, 0, 0.1)'
        };
        border-collapse: collapse;
        table-layout: fixed;
        box-sizing: border-box;
        overflow-x: auto;
        overflow-y: hidden;
        display: block;
        width: 100%;
        margin: 1.5rem 0;
      }
      .richtext-renderer table:first-child { margin-top: 0; }
      .richtext-renderer table:last-child { margin-bottom: 0; }
      .richtext-renderer table td, .richtext-renderer table th {
        border: 1px solid ${
          dark ? 'rgba(255, 255, 255, 0.2)' : 'rgba(0, 0, 0, 0.1)'
        };
        min-width: 1em;
        padding: 0.5rem;
        box-sizing: border-box;
        position: relative;
        text-align: left;
        vertical-align: top;
      }
      .richtext-renderer table td:first-of-type:not(a), .richtext-renderer table th:first-of-type:not(a) { margin-top: 0; }
      .richtext-renderer table td p, .richtext-renderer table th p { margin: 0; }
      .richtext-renderer table td p + p, .richtext-renderer table th p + p { margin-top: 0.75rem; }
      .richtext-renderer table th { font-weight: 700; text-align: left; }

      .richtext-renderer [data-text-align="left"] { text-align: left; }
      .richtext-renderer [data-text-align="center"] { text-align: center; }
      .richtext-renderer [data-text-align="right"] { text-align: right; }
      .richtext-renderer [data-text-align="justify"] { text-align: justify; }

      .richtext-renderer [data-indent="1"] { text-indent: 2em !important; }
      .richtext-renderer [data-indent="2"] { text-indent: 4em !important; }
      .richtext-renderer [data-indent="3"] { text-indent: 6em !important; }
      .richtext-renderer [data-indent="4"] { text-indent: 8em !important; }
      .richtext-renderer [data-indent="5"] { text-indent: 10em !important; }
      .richtext-renderer [data-indent="6"] { text-indent: 12em !important; }
      .richtext-renderer [data-indent="7"] { text-indent: 14em !important; }

      .richtext-renderer .columns { display: flex; gap: 1rem; margin: 1rem 0; }
      .richtext-renderer .column { flex: 1; min-width: 0; }
    </style>
  `;

  return (
    <div
      className={`richtext-renderer ${dark ? 'dark' : ''} ${className}`}
      style={baseStyles}
      dangerouslySetInnerHTML={{ __html: rendererStyles + content }}
    />
  );
};

export default RichTextRenderer;
